// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        (unknown)
// source: keyboard.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Layout int32

const (
	Layout_LAYOUT_UNSPECIFIED Layout = 0
	Layout_LAYOUT_QWERTY      Layout = 1
	Layout_LAYOUT_QWERTZ      Layout = 2
	Layout_LAYOUT_AZERTY      Layout = 3
)

// Enum value maps for Layout.
var (
	Layout_name = map[int32]string{
		0: "LAYOUT_UNSPECIFIED",
		1: "LAYOUT_QWERTY",
		2: "LAYOUT_QWERTZ",
		3: "LAYOUT_AZERTY",
	}
	Layout_value = map[string]int32{
		"LAYOUT_UNSPECIFIED": 0,
		"LAYOUT_QWERTY":      1,
		"LAYOUT_QWERTZ":      2,
		"LAYOUT_AZERTY":      3,
	}
)

func (x Layout) Enum() *Layout {
	p := new(Layout)
	*p = x
	return p
}

func (x Layout) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Layout) Descriptor() protoreflect.EnumDescriptor {
	return file_keyboard_proto_enumTypes[0].Descriptor()
}

func (Layout) Type() protoreflect.EnumType {
	return &file_keyboard_proto_enumTypes[0]
}

func (x Layout) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Layout.Descriptor instead.
func (Layout) EnumDescriptor() ([]byte, []int) {
	return file_keyboard_proto_rawDescGZIP(), []int{0}
}

type Keyboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layout        Layout                 `protobuf:"varint,1,opt,name=layout,proto3,enum=pb.Layout" json:"layout,omitempty"`
	Backlit       bool                   `protobuf:"varint,2,opt,name=backlit,proto3" json:"backlit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keyboard) Reset() {
	*x = Keyboard{}
	mi := &file_keyboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keyboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keyboard) ProtoMessage() {}

func (x *Keyboard) ProtoReflect() protoreflect.Message {
	mi := &file_keyboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keyboard.ProtoReflect.Descriptor instead.
func (*Keyboard) Descriptor() ([]byte, []int) {
	return file_keyboard_proto_rawDescGZIP(), []int{0}
}

func (x *Keyboard) GetLayout() Layout {
	if x != nil {
		return x.Layout
	}
	return Layout_LAYOUT_UNSPECIFIED
}

func (x *Keyboard) GetBacklit() bool {
	if x != nil {
		return x.Backlit
	}
	return false
}

var File_keyboard_proto protoreflect.FileDescriptor

var file_keyboard_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x48, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x12, 0x22, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x06, 0x6c, 0x61,
	0x79, 0x6f, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x62, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x74, 0x2a, 0x59,
	0x0a, 0x06, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x12, 0x4c, 0x41, 0x59, 0x4f,
	0x55, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x41, 0x59, 0x4f, 0x55, 0x54, 0x5f, 0x51, 0x57, 0x45, 0x52, 0x54,
	0x59, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x41, 0x59, 0x4f, 0x55, 0x54, 0x5f, 0x51, 0x57,
	0x45, 0x52, 0x54, 0x5a, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x41, 0x59, 0x4f, 0x55, 0x54,
	0x5f, 0x41, 0x5a, 0x45, 0x52, 0x54, 0x59, 0x10, 0x03, 0x42, 0x53, 0x0a, 0x06, 0x63, 0x6f, 0x6d,
	0x2e, 0x70, 0x62, 0x42, 0x0d, 0x4b, 0x65, 0x79, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x12, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0xa2, 0x02, 0x03, 0x50, 0x58, 0x58, 0xaa, 0x02,
	0x02, 0x50, 0x62, 0xca, 0x02, 0x02, 0x50, 0x62, 0xe2, 0x02, 0x0e, 0x50, 0x62, 0x5c, 0x47, 0x50,
	0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x02, 0x50, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_keyboard_proto_rawDescOnce sync.Once
	file_keyboard_proto_rawDescData = file_keyboard_proto_rawDesc
)

func file_keyboard_proto_rawDescGZIP() []byte {
	file_keyboard_proto_rawDescOnce.Do(func() {
		file_keyboard_proto_rawDescData = protoimpl.X.CompressGZIP(file_keyboard_proto_rawDescData)
	})
	return file_keyboard_proto_rawDescData
}

var file_keyboard_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_keyboard_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_keyboard_proto_goTypes = []any{
	(Layout)(0),      // 0: pb.Layout
	(*Keyboard)(nil), // 1: pb.Keyboard
}
var file_keyboard_proto_depIdxs = []int32{
	0, // 0: pb.Keyboard.layout:type_name -> pb.Layout
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_keyboard_proto_init() }
func file_keyboard_proto_init() {
	if File_keyboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_keyboard_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keyboard_proto_goTypes,
		DependencyIndexes: file_keyboard_proto_depIdxs,
		EnumInfos:         file_keyboard_proto_enumTypes,
		MessageInfos:      file_keyboard_proto_msgTypes,
	}.Build()
	File_keyboard_proto = out.File
	file_keyboard_proto_rawDesc = nil
	file_keyboard_proto_goTypes = nil
	file_keyboard_proto_depIdxs = nil
}
