// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: laptop.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Laptop struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand        string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Name         string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price        float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	ReleasedYear uint32                 `protobuf:"varint,5,opt,name=released_year,json=releasedYear,proto3" json:"released_year,omitempty"`
	Cpu          *CPU                   `protobuf:"bytes,6,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Ram          *Memory                `protobuf:"bytes,7,opt,name=ram,proto3" json:"ram,omitempty"`
	Screen       *Screen                `protobuf:"bytes,8,opt,name=screen,proto3" json:"screen,omitempty"`
	Keyboard     *Keyboard              `protobuf:"bytes,9,opt,name=keyboard,proto3" json:"keyboard,omitempty"`
	Gpuses       []*GPU                 `protobuf:"bytes,10,rep,name=gpuses,proto3" json:"gpuses,omitempty"`
	Storages     []*Storage             `protobuf:"bytes,11,rep,name=storages,proto3" json:"storages,omitempty"`
	// Types that are valid to be assigned to Weigth:
	//
	//	*Laptop_WeigthKg
	//	*Laptop_WeithLb
	Weigth        isLaptop_Weigth        `protobuf_oneof:"weigth"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Laptop) Reset() {
	*x = Laptop{}
	mi := &file_laptop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Laptop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Laptop) ProtoMessage() {}

func (x *Laptop) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Laptop.ProtoReflect.Descriptor instead.
func (*Laptop) Descriptor() ([]byte, []int) {
	return file_laptop_proto_rawDescGZIP(), []int{0}
}

func (x *Laptop) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Laptop) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Laptop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Laptop) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Laptop) GetReleasedYear() uint32 {
	if x != nil {
		return x.ReleasedYear
	}
	return 0
}

func (x *Laptop) GetCpu() *CPU {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *Laptop) GetRam() *Memory {
	if x != nil {
		return x.Ram
	}
	return nil
}

func (x *Laptop) GetScreen() *Screen {
	if x != nil {
		return x.Screen
	}
	return nil
}

func (x *Laptop) GetKeyboard() *Keyboard {
	if x != nil {
		return x.Keyboard
	}
	return nil
}

func (x *Laptop) GetGpuses() []*GPU {
	if x != nil {
		return x.Gpuses
	}
	return nil
}

func (x *Laptop) GetStorages() []*Storage {
	if x != nil {
		return x.Storages
	}
	return nil
}

func (x *Laptop) GetWeigth() isLaptop_Weigth {
	if x != nil {
		return x.Weigth
	}
	return nil
}

func (x *Laptop) GetWeigthKg() float64 {
	if x != nil {
		if x, ok := x.Weigth.(*Laptop_WeigthKg); ok {
			return x.WeigthKg
		}
	}
	return 0
}

func (x *Laptop) GetWeithLb() float64 {
	if x != nil {
		if x, ok := x.Weigth.(*Laptop_WeithLb); ok {
			return x.WeithLb
		}
	}
	return 0
}

func (x *Laptop) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type isLaptop_Weigth interface {
	isLaptop_Weigth()
}

type Laptop_WeigthKg struct {
	WeigthKg float64 `protobuf:"fixed64,12,opt,name=weigth_kg,json=weigthKg,proto3,oneof"`
}

type Laptop_WeithLb struct {
	WeithLb float64 `protobuf:"fixed64,13,opt,name=weith_lb,json=weithLb,proto3,oneof"`
}

func (*Laptop_WeigthKg) isLaptop_Weigth() {}

func (*Laptop_WeithLb) isLaptop_Weigth() {}

var File_laptop_proto protoreflect.FileDescriptor

const file_laptop_proto_rawDesc = "" +
	"\n" +
	"\flaptop.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0ekeyboard.proto\x1a\fmemory.proto\x1a\x0fprocessor.proto\x1a\fscreen.proto\x1a\rstorage.proto\"\xcf\x03\n" +
	"\x06Laptop\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12#\n" +
	"\rreleased_year\x18\x05 \x01(\rR\freleasedYear\x12\x19\n" +
	"\x03cpu\x18\x06 \x01(\v2\a.pb.CPUR\x03cpu\x12\x1c\n" +
	"\x03ram\x18\a \x01(\v2\n" +
	".pb.MemoryR\x03ram\x12\"\n" +
	"\x06screen\x18\b \x01(\v2\n" +
	".pb.ScreenR\x06screen\x12(\n" +
	"\bkeyboard\x18\t \x01(\v2\f.pb.KeyboardR\bkeyboard\x12\x1f\n" +
	"\x06gpuses\x18\n" +
	" \x03(\v2\a.pb.GPUR\x06gpuses\x12'\n" +
	"\bstorages\x18\v \x03(\v2\v.pb.StorageR\bstorages\x12\x1d\n" +
	"\tweigth_kg\x18\f \x01(\x01H\x00R\bweigthKg\x12\x1b\n" +
	"\bweith_lb\x18\r \x01(\x01H\x00R\aweithLb\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\b\n" +
	"\x06weigthBQ\n" +
	"\x06com.pbB\vLaptopProtoP\x01Z\x12matrix/internal/pb\xa2\x02\x03PXX\xaa\x02\x02Pb\xca\x02\x02Pb\xe2\x02\x0ePb\\GPBMetadata\xea\x02\x02Pbb\x06proto3"

var (
	file_laptop_proto_rawDescOnce sync.Once
	file_laptop_proto_rawDescData []byte
)

func file_laptop_proto_rawDescGZIP() []byte {
	file_laptop_proto_rawDescOnce.Do(func() {
		file_laptop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_laptop_proto_rawDesc), len(file_laptop_proto_rawDesc)))
	})
	return file_laptop_proto_rawDescData
}

var file_laptop_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_laptop_proto_goTypes = []any{
	(*Laptop)(nil),                // 0: pb.Laptop
	(*CPU)(nil),                   // 1: pb.CPU
	(*Memory)(nil),                // 2: pb.Memory
	(*Screen)(nil),                // 3: pb.Screen
	(*Keyboard)(nil),              // 4: pb.Keyboard
	(*GPU)(nil),                   // 5: pb.GPU
	(*Storage)(nil),               // 6: pb.Storage
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_laptop_proto_depIdxs = []int32{
	1, // 0: pb.Laptop.cpu:type_name -> pb.CPU
	2, // 1: pb.Laptop.ram:type_name -> pb.Memory
	3, // 2: pb.Laptop.screen:type_name -> pb.Screen
	4, // 3: pb.Laptop.keyboard:type_name -> pb.Keyboard
	5, // 4: pb.Laptop.gpuses:type_name -> pb.GPU
	6, // 5: pb.Laptop.storages:type_name -> pb.Storage
	7, // 6: pb.Laptop.updated_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_laptop_proto_init() }
func file_laptop_proto_init() {
	if File_laptop_proto != nil {
		return
	}
	file_keyboard_proto_init()
	file_memory_proto_init()
	file_processor_proto_init()
	file_screen_proto_init()
	file_storage_proto_init()
	file_laptop_proto_msgTypes[0].OneofWrappers = []any{
		(*Laptop_WeigthKg)(nil),
		(*Laptop_WeithLb)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_laptop_proto_rawDesc), len(file_laptop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_laptop_proto_goTypes,
		DependencyIndexes: file_laptop_proto_depIdxs,
		MessageInfos:      file_laptop_proto_msgTypes,
	}.Build()
	File_laptop_proto = out.File
	file_laptop_proto_goTypes = nil
	file_laptop_proto_depIdxs = nil
}
