// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        (unknown)
// source: screen.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Panel int32

const (
	Panel_PANEL_UNSPECIFIED Panel = 0
	Panel_PANEL_IPS         Panel = 1
	Panel_PANEL_OLED        Panel = 2
)

// Enum value maps for Panel.
var (
	Panel_name = map[int32]string{
		0: "PANEL_UNSPECIFIED",
		1: "PANEL_IPS",
		2: "PANEL_OLED",
	}
	Panel_value = map[string]int32{
		"PANEL_UNSPECIFIED": 0,
		"PANEL_IPS":         1,
		"PANEL_OLED":        2,
	}
)

func (x Panel) Enum() *Panel {
	p := new(Panel)
	*p = x
	return p
}

func (x Panel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Panel) Descriptor() protoreflect.EnumDescriptor {
	return file_screen_proto_enumTypes[0].Descriptor()
}

func (Panel) Type() protoreflect.EnumType {
	return &file_screen_proto_enumTypes[0]
}

func (x Panel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Panel.Descriptor instead.
func (Panel) EnumDescriptor() ([]byte, []int) {
	return file_screen_proto_rawDescGZIP(), []int{0}
}

type Resolution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width  uint32 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height uint32 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *Resolution) Reset() {
	*x = Resolution{}
	mi := &file_screen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resolution) ProtoMessage() {}

func (x *Resolution) ProtoReflect() protoreflect.Message {
	mi := &file_screen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resolution.ProtoReflect.Descriptor instead.
func (*Resolution) Descriptor() ([]byte, []int) {
	return file_screen_proto_rawDescGZIP(), []int{0}
}

func (x *Resolution) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Resolution) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Screen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SizeInch   float32     `protobuf:"fixed32,1,opt,name=size_inch,json=sizeInch,proto3" json:"size_inch,omitempty"`
	Resolution *Resolution `protobuf:"bytes,2,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Panel      Panel       `protobuf:"varint,3,opt,name=panel,proto3,enum=pb.Panel" json:"panel,omitempty"`
	Multitouch bool        `protobuf:"varint,4,opt,name=multitouch,proto3" json:"multitouch,omitempty"`
}

func (x *Screen) Reset() {
	*x = Screen{}
	mi := &file_screen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Screen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Screen) ProtoMessage() {}

func (x *Screen) ProtoReflect() protoreflect.Message {
	mi := &file_screen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Screen.ProtoReflect.Descriptor instead.
func (*Screen) Descriptor() ([]byte, []int) {
	return file_screen_proto_rawDescGZIP(), []int{1}
}

func (x *Screen) GetSizeInch() float32 {
	if x != nil {
		return x.SizeInch
	}
	return 0
}

func (x *Screen) GetResolution() *Resolution {
	if x != nil {
		return x.Resolution
	}
	return nil
}

func (x *Screen) GetPanel() Panel {
	if x != nil {
		return x.Panel
	}
	return Panel_PANEL_UNSPECIFIED
}

func (x *Screen) GetMultitouch() bool {
	if x != nil {
		return x.Multitouch
	}
	return false
}

var File_screen_proto protoreflect.FileDescriptor

var file_screen_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x3a, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x96,
	0x01, 0x0a, 0x06, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x69, 0x7a,
	0x65, 0x5f, 0x69, 0x6e, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x73, 0x69,
	0x7a, 0x65, 0x49, 0x6e, 0x63, 0x68, 0x12, 0x2e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f,
	0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x05, 0x70, 0x61, 0x6e, 0x65, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x6e, 0x65, 0x6c,
	0x52, 0x05, 0x70, 0x61, 0x6e, 0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x75, 0x6c, 0x74, 0x69,
	0x74, 0x6f, 0x75, 0x63, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x6d, 0x75, 0x6c,
	0x74, 0x69, 0x74, 0x6f, 0x75, 0x63, 0x68, 0x2a, 0x3d, 0x0a, 0x05, 0x50, 0x61, 0x6e, 0x65, 0x6c,
	0x12, 0x15, 0x0a, 0x11, 0x50, 0x41, 0x4e, 0x45, 0x4c, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x41, 0x4e, 0x45, 0x4c,
	0x5f, 0x49, 0x50, 0x53, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x41, 0x4e, 0x45, 0x4c, 0x5f,
	0x4f, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x42, 0x54, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x62,
	0x42, 0x0b, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x15, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0xa2, 0x02, 0x03, 0x50, 0x58, 0x58, 0xaa, 0x02, 0x02, 0x50,
	0x62, 0xca, 0x02, 0x02, 0x50, 0x62, 0xe2, 0x02, 0x0e, 0x50, 0x62, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x02, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_screen_proto_rawDescOnce sync.Once
	file_screen_proto_rawDescData = file_screen_proto_rawDesc
)

func file_screen_proto_rawDescGZIP() []byte {
	file_screen_proto_rawDescOnce.Do(func() {
		file_screen_proto_rawDescData = protoimpl.X.CompressGZIP(file_screen_proto_rawDescData)
	})
	return file_screen_proto_rawDescData
}

var file_screen_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_screen_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_screen_proto_goTypes = []any{
	(Panel)(0),         // 0: pb.Panel
	(*Resolution)(nil), // 1: pb.Resolution
	(*Screen)(nil),     // 2: pb.Screen
}
var file_screen_proto_depIdxs = []int32{
	1, // 0: pb.Screen.resolution:type_name -> pb.Resolution
	0, // 1: pb.Screen.panel:type_name -> pb.Panel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_screen_proto_init() }
func file_screen_proto_init() {
	if File_screen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_screen_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_screen_proto_goTypes,
		DependencyIndexes: file_screen_proto_depIdxs,
		EnumInfos:         file_screen_proto_enumTypes,
		MessageInfos:      file_screen_proto_msgTypes,
	}.Build()
	File_screen_proto = out.File
	file_screen_proto_rawDesc = nil
	file_screen_proto_goTypes = nil
	file_screen_proto_depIdxs = nil
}
