// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: screen.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Panel int32

const (
	Panel_PANEL_UNSPECIFIED Panel = 0
	Panel_PANEL_IPS         Panel = 1
	Panel_PANEL_OLED        Panel = 2
)

// Enum value maps for Panel.
var (
	Panel_name = map[int32]string{
		0: "PANEL_UNSPECIFIED",
		1: "PANEL_IPS",
		2: "PANEL_OLED",
	}
	Panel_value = map[string]int32{
		"PANEL_UNSPECIFIED": 0,
		"PANEL_IPS":         1,
		"PANEL_OLED":        2,
	}
)

func (x Panel) Enum() *Panel {
	p := new(Panel)
	*p = x
	return p
}

func (x Panel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Panel) Descriptor() protoreflect.EnumDescriptor {
	return file_screen_proto_enumTypes[0].Descriptor()
}

func (Panel) Type() protoreflect.EnumType {
	return &file_screen_proto_enumTypes[0]
}

func (x Panel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Panel.Descriptor instead.
func (Panel) EnumDescriptor() ([]byte, []int) {
	return file_screen_proto_rawDescGZIP(), []int{0}
}

type Resolution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resolution) Reset() {
	*x = Resolution{}
	mi := &file_screen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resolution) ProtoMessage() {}

func (x *Resolution) ProtoReflect() protoreflect.Message {
	mi := &file_screen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resolution.ProtoReflect.Descriptor instead.
func (*Resolution) Descriptor() ([]byte, []int) {
	return file_screen_proto_rawDescGZIP(), []int{0}
}

func (x *Resolution) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Resolution) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Screen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SizeInch      float32                `protobuf:"fixed32,1,opt,name=size_inch,json=sizeInch,proto3" json:"size_inch,omitempty"`
	Resolution    *Resolution            `protobuf:"bytes,2,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Panel         Panel                  `protobuf:"varint,3,opt,name=panel,proto3,enum=pb.Panel" json:"panel,omitempty"`
	Multitouch    bool                   `protobuf:"varint,4,opt,name=multitouch,proto3" json:"multitouch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Screen) Reset() {
	*x = Screen{}
	mi := &file_screen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Screen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Screen) ProtoMessage() {}

func (x *Screen) ProtoReflect() protoreflect.Message {
	mi := &file_screen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Screen.ProtoReflect.Descriptor instead.
func (*Screen) Descriptor() ([]byte, []int) {
	return file_screen_proto_rawDescGZIP(), []int{1}
}

func (x *Screen) GetSizeInch() float32 {
	if x != nil {
		return x.SizeInch
	}
	return 0
}

func (x *Screen) GetResolution() *Resolution {
	if x != nil {
		return x.Resolution
	}
	return nil
}

func (x *Screen) GetPanel() Panel {
	if x != nil {
		return x.Panel
	}
	return Panel_PANEL_UNSPECIFIED
}

func (x *Screen) GetMultitouch() bool {
	if x != nil {
		return x.Multitouch
	}
	return false
}

var File_screen_proto protoreflect.FileDescriptor

const file_screen_proto_rawDesc = "" +
	"\n" +
	"\fscreen.proto\x12\x02pb\":\n" +
	"\n" +
	"Resolution\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\"\x96\x01\n" +
	"\x06Screen\x12\x1b\n" +
	"\tsize_inch\x18\x01 \x01(\x02R\bsizeInch\x12.\n" +
	"\n" +
	"resolution\x18\x02 \x01(\v2\x0e.pb.ResolutionR\n" +
	"resolution\x12\x1f\n" +
	"\x05panel\x18\x03 \x01(\x0e2\t.pb.PanelR\x05panel\x12\x1e\n" +
	"\n" +
	"multitouch\x18\x04 \x01(\bR\n" +
	"multitouch*=\n" +
	"\x05Panel\x12\x15\n" +
	"\x11PANEL_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tPANEL_IPS\x10\x01\x12\x0e\n" +
	"\n" +
	"PANEL_OLED\x10\x02BQ\n" +
	"\x06com.pbB\vScreenProtoP\x01Z\x12matrix/internal/pb\xa2\x02\x03PXX\xaa\x02\x02Pb\xca\x02\x02Pb\xe2\x02\x0ePb\\GPBMetadata\xea\x02\x02Pbb\x06proto3"

var (
	file_screen_proto_rawDescOnce sync.Once
	file_screen_proto_rawDescData []byte
)

func file_screen_proto_rawDescGZIP() []byte {
	file_screen_proto_rawDescOnce.Do(func() {
		file_screen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_screen_proto_rawDesc), len(file_screen_proto_rawDesc)))
	})
	return file_screen_proto_rawDescData
}

var file_screen_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_screen_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_screen_proto_goTypes = []any{
	(Panel)(0),         // 0: pb.Panel
	(*Resolution)(nil), // 1: pb.Resolution
	(*Screen)(nil),     // 2: pb.Screen
}
var file_screen_proto_depIdxs = []int32{
	1, // 0: pb.Screen.resolution:type_name -> pb.Resolution
	0, // 1: pb.Screen.panel:type_name -> pb.Panel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_screen_proto_init() }
func file_screen_proto_init() {
	if File_screen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_screen_proto_rawDesc), len(file_screen_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_screen_proto_goTypes,
		DependencyIndexes: file_screen_proto_depIdxs,
		EnumInfos:         file_screen_proto_enumTypes,
		MessageInfos:      file_screen_proto_msgTypes,
	}.Build()
	File_screen_proto = out.File
	file_screen_proto_goTypes = nil
	file_screen_proto_depIdxs = nil
}
