// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        (unknown)
// source: stroage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Driver int32

const (
	Driver_DRIVER_UNSPECIFIED Driver = 0
	Driver_DRIVER_HDD         Driver = 1
	Driver_DRIVER_SSD         Driver = 2
)

// Enum value maps for Driver.
var (
	Driver_name = map[int32]string{
		0: "DRIVER_UNSPECIFIED",
		1: "DRIVER_HDD",
		2: "DRIVER_SSD",
	}
	Driver_value = map[string]int32{
		"DRIVER_UNSPECIFIED": 0,
		"DRIVER_HDD":         1,
		"DRIVER_SSD":         2,
	}
)

func (x Driver) Enum() *Driver {
	p := new(Driver)
	*p = x
	return p
}

func (x Driver) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Driver) Descriptor() protoreflect.EnumDescriptor {
	return file_stroage_proto_enumTypes[0].Descriptor()
}

func (Driver) Type() protoreflect.EnumType {
	return &file_stroage_proto_enumTypes[0]
}

func (x Driver) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Driver.Descriptor instead.
func (Driver) EnumDescriptor() ([]byte, []int) {
	return file_stroage_proto_rawDescGZIP(), []int{0}
}

type Stroage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Driver Driver  `protobuf:"varint,1,opt,name=driver,proto3,enum=pb.Driver" json:"driver,omitempty"`
	Memory *Memory `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
}

func (x *Stroage) Reset() {
	*x = Stroage{}
	mi := &file_stroage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stroage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stroage) ProtoMessage() {}

func (x *Stroage) ProtoReflect() protoreflect.Message {
	mi := &file_stroage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stroage.ProtoReflect.Descriptor instead.
func (*Stroage) Descriptor() ([]byte, []int) {
	return file_stroage_proto_rawDescGZIP(), []int{0}
}

func (x *Stroage) GetDriver() Driver {
	if x != nil {
		return x.Driver
	}
	return Driver_DRIVER_UNSPECIFIED
}

func (x *Stroage) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

var File_stroage_proto protoreflect.FileDescriptor

var file_stroage_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x74, 0x72, 0x6f, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x1a, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x51, 0x0a, 0x07, 0x53, 0x74, 0x72, 0x6f, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x06,
	0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x70,
	0x62, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x52, 0x06, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72,
	0x12, 0x22, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x06, 0x6d, 0x65,
	0x6d, 0x6f, 0x72, 0x79, 0x2a, 0x40, 0x0a, 0x06, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x12, 0x44, 0x52, 0x49, 0x56, 0x45, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x52, 0x49, 0x56, 0x45, 0x52,
	0x5f, 0x48, 0x44, 0x44, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x52, 0x49, 0x56, 0x45, 0x52,
	0x5f, 0x53, 0x53, 0x44, 0x10, 0x02, 0x42, 0x52, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x62,
	0x42, 0x0c, 0x53, 0x74, 0x72, 0x6f, 0x61, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x12, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x62, 0xa2, 0x02, 0x03, 0x50, 0x58, 0x58, 0xaa, 0x02, 0x02, 0x50, 0x62, 0xca,
	0x02, 0x02, 0x50, 0x62, 0xe2, 0x02, 0x0e, 0x50, 0x62, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x02, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_stroage_proto_rawDescOnce sync.Once
	file_stroage_proto_rawDescData = file_stroage_proto_rawDesc
)

func file_stroage_proto_rawDescGZIP() []byte {
	file_stroage_proto_rawDescOnce.Do(func() {
		file_stroage_proto_rawDescData = protoimpl.X.CompressGZIP(file_stroage_proto_rawDescData)
	})
	return file_stroage_proto_rawDescData
}

var file_stroage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stroage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stroage_proto_goTypes = []any{
	(Driver)(0),     // 0: pb.Driver
	(*Stroage)(nil), // 1: pb.Stroage
	(*Memory)(nil),  // 2: pb.Memory
}
var file_stroage_proto_depIdxs = []int32{
	0, // 0: pb.Stroage.driver:type_name -> pb.Driver
	2, // 1: pb.Stroage.memory:type_name -> pb.Memory
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stroage_proto_init() }
func file_stroage_proto_init() {
	if File_stroage_proto != nil {
		return
	}
	file_memory_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stroage_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stroage_proto_goTypes,
		DependencyIndexes: file_stroage_proto_depIdxs,
		EnumInfos:         file_stroage_proto_enumTypes,
		MessageInfos:      file_stroage_proto_msgTypes,
	}.Build()
	File_stroage_proto = out.File
	file_stroage_proto_rawDesc = nil
	file_stroage_proto_goTypes = nil
	file_stroage_proto_depIdxs = nil
}
