CREATE TABLE stocks (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    price VARCHAR(20),
    company VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
